// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"GALV_MessageStylesMZ","status":true,"description":"(v.2.1) 'Show Text' windows float above characters and change visuals during game.","parameters":{"iIndicator":"2,0,-12","mPadding":"0,0,0,0","invertPos":"false","aGraphic":"WindowArrow","yOffset":"60"}},
{"name":"ButtonPicture","status":true,"description":"Makes a picture clickable.","parameters":{}},
{"name":"MenuLegal","status":true,"description":"Menu PNS","parameters":{}},
{"name":"FimLegal","status":true,"description":"","parameters":{}},
{"name":"QuestBook","status":true,"description":"(v.1.3) A system to track quests/sidequests in your RPG.","parameters":{"File":"Quests","Folder":"data","- OPTIONS -":"","Font Size":"22","Categories":"Main Quests|#ffcc66,Side Quests|#ffff99,Crafting Quests|#ccccff","-- ICONS --":"","Not Complete Icon":"163","Complete Icon":"164","Failed Icon":"162","Tracked Quest Icon":"88","-- VOCAB --":"","Quest Command":"Quest Log","Active Cmd Txt":"Active","Completed Cmd Txt":"Complete","Failed Cmd Txt":"Failed","No Tracked Quest":"No Quest Selected","-- EXTRA --":"","Pop XY":"20,20","Pop Time":"130","Pop New Quest":"New Quest:","Pop Complete Quest":"Quest Completed:","Pop Fail Quest":"Quest Failed:","Pop New Objective":"New Objective:","Pop Complete Objective":"Objective Completed:","Pop Fail Objective":"Objective Failed:"}},
{"name":"Save legal","status":true,"description":"Save legal","parameters":{}},
{"name":"Option Legal","status":true,"description":"Menu PNS","parameters":{}},
{"name":"Equip legal","status":true,"description":"Equipamentos legal","parameters":{}},
{"name":"changeTileSize","status":true,"description":"Allows you to use tiles of a different size in game.","parameters":{"Tile Size":"72","Key String":"!"}},
{"name":"Community_Lighting_MZ","status":true,"description":"v4.3 Creates an extra layer that darkens a map and adds lightsources! Released under the MIT license!","parameters":{"---General Settings---":"","Options Menu Entry":"Lighting Effects","Light event required":"false","Shift lights with events":"false","Reset Lights":"false","Kill Switch":"None","Kill Switch Auto":"false","Note Tag Key":"cl","---DayNight Settings---":"","Save DaynightHours":"0","Save DaynightMinutes":"0","Save DaynightSeconds":"0","Save Night Switch":"0","Night Hours":"0, 1, 2, 3, 4, 5, 6, 19, 20, 21, 22, 23","DayNight Colors":"[\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#9999ff\",\"#ccccff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffffff\",\"#ffcc88\",\"#9999ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\",\"#6666ff\"]","---Offset and Sizes---":"","Player radius":"0","Flashlight offset":"0","Screensize X":"1024","Screensize Y":"768","Lightmask Padding":"32","---Battle Settings---":"","Battle Tinting":"true","Light Mask Position":"Above"}},
{"name":"Suspects","status":true,"description":"Suspects","parameters":{}}
];
